version: '2.4'

services: 
  iris:
    build: 
      context: .
      args:
        USER: ${DEMO_USER}
        PASS: ${DEMO_PASS}
        NAMESPACE: ${DEMO_NAMESPACE}
    ports:
      - ${WEB_PORT}:80
      - ${IRIS_PORT}:52773
    volumes:
      - ./php/demo:/var/www/html
